### PR TITLE
Update requirements.txt with new version of tables

### PR DESCRIPTION
**Pull request by adamwarnerbring**
## Summary

This pull request introduces the following changes

* Update tables from 3.7.0 to 3.9.2 in requirements

Relates to the following issues

* Problem with pip install tables==3.7.0

## Conformity
- [x] [Changelog entry](https://github.com/umami-hep/puma/blob/main/changelog.md)
- [x] [Documentation](https://umami-hep.github.io/puma/)

### CODE REVIEW

**Comment by samvanstroud** [comment]
Can you try using tables 3.9.0? https://github.com/umami-hep/puma/actions/runs/8064748846/job/22029246476?pr=245#step:7:43

**Comment by adamwarnerbring** [comment]
Looks like tables==3.9.0 does not work either.

**Comment by dkobylianskii** [comment]
Hi @adamwarnerbring,
Can you try pytables 3.8.0 on your side?
Does it work for you?

We can't use a version later than this without dropping Python 3.8 support.

**Comment by adamwarnerbring** [comment]
> Hi @adamwarnerbring, Can you try tables==3.8.0 on your side? Does it work for you?
> 
> We can't use a version later than this without dropping Python 3.8 support.
> 
> Or should we drop it? @samvanstroud

Hi @dkobylianskii, tables==3.8.0 works on my side

**Comment by dkobylianskii** [comment]
Nice,
So my suggestion is to use `tables=3.8.0` and keep Python 3.8. Because other packages (`atlas-ftag-tools` and `upp`) support it.

**Comment by adamwarnerbring** [comment]
Yes, will do. Thanks for the help!

**Review by dkobylianskii — APPROVED** [review]

**Pull request merged**
