### PR TITLE
ROC improvements

### PR DESCRIPTION
**Pull request by samvanstroud**
## Summary

This pull request introduces the following changes

* Improve ROC plot format
* Use auto figsize, and add support for more than two ratio panels
* Simplifications - use constrained instead of tight layout, `plot_base` handles grids

Relates to the following issues

* #148 

## Conformity
- [x] [Changelog entry](https://github.com/umami-hep/puma/blob/main/changelog.md)
- [x] [Documentation](https://umami-hep.github.io/puma/)

### CODE REVIEW

**Comment by samvanstroud** [comment]
@jobirk @afroch, I noticed some deviations from the black format style, do you want me to fix them in this MR?

**Comment by samvanstroud** [comment]
Here is a file showing the changes, affecting the high level plots API
[pull.pdf](https://github.com/umami-hep/puma/files/10730995/pull.pdf)

**Comment by afroch** [comment]
> @jobirk @afroch, I noticed some deviations from the black format style, do you want me to fix them in this MR?

Hi @samvanstroud. Yes, if you want, you can add the fix for black here if you want

**Comment by afroch** [comment]
> Here is a file showing the changes, affecting the high level plots API [pull.pdf](https://github.com/umami-hep/puma/files/10730995/pull.pdf)

Could you maybe also provide an example with the ratio plot on?

**Comment by samvanstroud** [comment]
> > @jobirk @afroch, I noticed some deviations from the black format style, do you want me to fix them in this MR?
> 
> Hi @samvanstroud. Yes, if you want, you can add the fix for black here if you want

Done

**Comment by afroch** [comment]
> > > Here is a file showing the changes, affecting the high level plots API [pull.pdf](https://github.com/umami-hep/puma/files/10730995/pull.pdf)
> > 
> > 
> > Could you maybe also provide an example with the ratio plot on?
> 
> @afroch Do you mean to upload a plot here? or provide an example in the code.
> 
> I turned the ratio off as since the discriminants can have different ranges, the ratio can explode.

Can you provide one here. Just to see how it looks with the new plot_base approach

**Comment by samvanstroud** [comment]
@afroch here you go :)
hlplots_disc_b

**Pull request closed without merging**
