### PR TITLE
Update names of aux variables

### PR DESCRIPTION
**Pull request by jmw464**
## Summary

This pull request introduces the following changes

* Updated names of aux task output variables to match Salt

## Conformity
- [x] [Changelog entry](https://github.com/umami-hep/puma/blob/main/changelog.md)
- [x] [Documentation](https://umami-hep.github.io/puma/)

### CODE REVIEW

**Comment by dkobylianskii** [comment]
Hi @jmw464 ,
Did the `salt` output names change? I don't see it in [TDD](https://gitlab.cern.ch/atlas-flavor-tagging-tools/training-dataset-dumper/-/blob/main/configs/EMPFlow.json?ref_type=heads#L60) and [Salt](https://gitlab.cern.ch/atlas-flavor-tagging-tools/algorithms/salt/-/blob/main/salt/models/task.py?ref_type=heads#L518). 
Do you think we should hold this MR for now?

**Comment by jmw464** [comment]
> Hi @jmw464 , Did the `salt` output names change? I don't see it in [TDD](https://gitlab.cern.ch/atlas-flavor-tagging-tools/training-dataset-dumper/-/blob/main/configs/EMPFlow.json?ref_type=heads#L60) and [Salt](https://gitlab.cern.ch/atlas-flavor-tagging-tools/algorithms/salt/-/blob/main/salt/models/task.py?ref_type=heads#L518). Do you think we should hold this MR for now?

Hi @dkobylianskii I did this based on some of the recent samples so maybe this is only a change in Athena. Let me see what's going on, we can hold off on this for now.

**Comment by samvanstroud** [comment]
At one point we had GN2 running twice, this was fixed here https://gitlab.cern.ch/atlas-flavor-tagging-tools/training-dataset-dumper/-/commit/c1c4cee591dea9842387a76d3fef79770efeb735, we just kept `GN2v01_aux_TrackOrigin` now

**Comment by samvanstroud** [comment]
In the latest dumps we have switched to `GN2v01_aux_TrackOrigin` etc, @jmw464 can you update this PR accordingly? Thanks!

**Comment by jmw464** [comment]
Ok done @samvanstroud!

**Review by samvanstroud — APPROVED** [review]

**Pull request merged**
